name = "starter-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
WEB_URL = "http://localhost:3000"
ADMIN_URL = "http://localhost:3001"

[env.production.vars]
ENVIRONMENT = "production"
WEB_URL = "https://congenial-disco-web.vercel.app"
ADMIN_URL = "http://localhost:3001"
